name: verdiscom
description: an app for communications in the verdis government

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a+.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  easy_dynamic_theme: ^2.2.0
  statusbarz: ^1.0.6
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  url_launcher: ^6.0.18
  webfeed: ^0.7.0
  image_picker: ^0.8.4+4

  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.6
  cloud_firestore: ^3.1.7
  flutter_native_splash: ^1.3.3
  tab_indicator_styler: ^2.0.0
  configurable_expansion_tile_null_safety: ^2.0.0
  mime: ^1.0.1
  file_selector: ^0.8.2+1
  file_selector_macos: ^0.0.4+1
  adaptive_dialog: ^1.3.0
  flutterfire_ui: ^0.3.1
  package_info_plus: ^1.3.0

  edge_alerts: ^0.0.1
  flutter_chat_ui: ^1.5.4
  flutter_firebase_chat_core: ^1.5.2
  open_file: ^3.2.1
  file_picker: ^4.3.2
  editable_image: ^0.3.0
  universal_io: ^2.0.4
  contactus: ^1.2.0
  jitsi_meet_wrapper: ^0.0.2
  uzu_flavored_markdown:
    path: ./uzu_flavored_markdown
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  cloud_functions: ^3.2.5
  azlistview: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  test: ^1.17.10

dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
      ref: "304770"
  flutter_launcher_icons:
    git:
      url: https://github.com/SimonIT/flutter_launcher_icons.git

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_foreground_scale_factor: 0.33

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icon/app_icon.svg
    - assets/icon/banner.svg
    - assets/images/garv.jpg
    - assets/images/banner.png
    - assets/images/banner-dark.png
    - assets/images/ic_index_bar_bubble_white.png
  fonts:
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#24347d"
  # background_image: assets/images/background.png

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/images/splash_screen.png

  # This property allows you to specify an image used as branding in the splash screen. It must be
  # a png file. Currently, it is only supported for Android and iOS.
  # branding: assets/dart.png

  # Specify your branding image for dark mode.
  # branding_dark: assets/dart_dark.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #
  # Make sure this content mode value should not be similar to android_gravity value and ios_content_mode
  # value.
  #branding_mode: bottom

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'