// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsphs0mmZoy7oSR3jBDQQregOK7skXQcA',
    appId: '1:686272364376:web:8fc8358d4338495d236f2d',
    messagingSenderId: '686272364376',
    projectId: 'verdis-communications',
    authDomain: 'verdis-communications.firebaseapp.com',
    databaseURL: 'https://verdis-communications-default-rtdb.firebaseio.com',
    storageBucket: 'verdis-communications.appspot.com',
    measurementId: 'G-5WGE7QBPRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDX9sch62oACNza97UgdjuTc_Ata6Vt4',
    appId: '1:686272364376:android:4eeb2432b600f7b7236f2d',
    messagingSenderId: '686272364376',
    projectId: 'verdis-communications',
    databaseURL: 'https://verdis-communications-default-rtdb.firebaseio.com',
    storageBucket: 'verdis-communications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSw44JdWOm-m0TzXgCRG1PgpTEKcmlRtA',
    appId: '1:686272364376:ios:b268fa09ef2de76c236f2d',
    messagingSenderId: '686272364376',
    projectId: 'verdis-communications',
    databaseURL: 'https://verdis-communications-default-rtdb.firebaseio.com',
    storageBucket: 'verdis-communications.appspot.com',
    androidClientId: '686272364376-59mekiltghksl8qjprjqldkhqg69ik95.apps.googleusercontent.com',
    iosClientId: '686272364376-vtfumiv5sbu519jt58atmf8t0fkdir2n.apps.googleusercontent.com',
    iosBundleId: 'com.garv.verdiscom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSw44JdWOm-m0TzXgCRG1PgpTEKcmlRtA',
    appId: '1:686272364376:ios:b268fa09ef2de76c236f2d',
    messagingSenderId: '686272364376',
    projectId: 'verdis-communications',
    databaseURL: 'https://verdis-communications-default-rtdb.firebaseio.com',
    storageBucket: 'verdis-communications.appspot.com',
    androidClientId: '686272364376-59mekiltghksl8qjprjqldkhqg69ik95.apps.googleusercontent.com',
    iosClientId: '686272364376-vtfumiv5sbu519jt58atmf8t0fkdir2n.apps.googleusercontent.com',
    iosBundleId: 'com.garv.verdiscom',
  );
}
